//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ionx.Entity.GatewayAnalytics.Settings
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnalyticsConfig
    {
        public System.Guid GatewayGuid { get; set; }
        public string TeamViewerID { get; set; }
    }
}
