//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ionx.Entity.GatewayAnalytics.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disk
    {
        public long DiskID { get; set; }
        public System.Guid GatewayGuid { get; set; }
        public string Label { get; set; }
        public long TotalSpace { get; set; }
        public long UsedSpace { get; set; }
    
        public virtual Gateway Gateway { get; set; }
    }
}
