//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ionx.Entity.GatewayAnalytics.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GatewayAnalyticsEntities : DbContext
    {
        public GatewayAnalyticsEntities()
            : base("name=GatewayAnalyticsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Disk> Disks { get; set; }
        public virtual DbSet<Gateway> Gateways { get; set; }
        public virtual DbSet<LatestEvent> LatestEvents { get; set; }
        public virtual DbSet<PerformanceMetric> PerformanceMetrics { get; set; }
        public virtual DbSet<Service> Services { get; set; }
    }
}
