//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ionx.Entity.GatewayAnalytics.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gateway
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gateway()
        {
            this.Disks = new HashSet<Disk>();
            this.LatestEvents = new HashSet<LatestEvent>();
            this.Services = new HashSet<Service>();
        }
    
        public System.Guid GatewayGuid { get; set; }
        public string TeamViewerID { get; set; }
        public string MachineName { get; set; }
        public System.DateTime LastReportDate { get; set; }
        public Nullable<System.DateTime> RunningSince { get; set; }
        public string OperatingSystem { get; set; }
        public string CpuInfo { get; set; }
        public Nullable<long> MemorySize { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<System.DateTime> LocationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Disk> Disks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LatestEvent> LatestEvents { get; set; }
        public virtual PerformanceMetric PerformanceMetric { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service> Services { get; set; }
    }
}
