//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ionx.Entity.GatewayAnalytics.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LatestEvent
    {
        public long EventID { get; set; }
        public System.Guid GatewayGuid { get; set; }
        public System.DateTime EventDateUtc { get; set; }
        public string EventName { get; set; }
        public string EventInfo { get; set; }
        public string AssetName { get; set; }
    
        public virtual Gateway Gateway { get; set; }
    }
}
