//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ionx.Entity.GatewayAnalytics.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerformanceMetric
    {
        public System.Guid GatewayGuid { get; set; }
        public Nullable<int> TotalEventsProcessed { get; set; }
        public Nullable<int> EventsProcessedPerSec { get; set; }
        public Nullable<int> CurrentSignalQuality { get; set; }
        public Nullable<int> AverageSignalQuality { get; set; }
        public Nullable<int> Reliability { get; set; }
        public Nullable<int> Stability { get; set; }
        public Nullable<int> Latency { get; set; }
        public Nullable<int> ConnectedNodes { get; set; }
    
        public virtual Gateway Gateway { get; set; }
    }
}
