//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ionx.Entity.GatewayAnalytics.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public long ServiceID { get; set; }
        public System.Guid GatewayGuid { get; set; }
        public string ServiceName { get; set; }
        public string Status { get; set; }
    
        public virtual Gateway Gateway { get; set; }
    }
}
